# Generated by Django 5.0.6 on 2024-05-11 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pokemon_id', models.IntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('types', models.JSONField()),
                ('abilities', models.JSONField()),
                ('base_stats', models.JSONField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sprite_url', models.URLField()),
                ('score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSafe',
            fields=[
                ('pokemon_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('types', models.JSONField()),
                ('abilities', models.JSONField()),
                ('base_stats', models.JSONField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sprite_url', models.URLField()),
                ('score', models.FloatField(null=True)),
            ],
        ),
    ]
