# Generated by Django 5.0.6 on 2024-05-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApiDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemontable',
            name='id',
        ),
        migrations.AlterField(
            model_name='pokemontable',
            name='pokemon_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
