# Generated by Django 5.0.6 on 2024-05-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApiDjango', '0003_rename_pokemontable_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='score',
            field=models.FloatField(default=float),
            preserve_default=False,
        ),
    ]
